#!/bin/bash
### BEGIN INIT INFO
# Provides:          <NAME>
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       <DESCRIPTION>
### END INIT INFO

start() {
  echo "Starting hp_netscan"
  start-stop-daemon --start --exec /usr/share/hp-netscan/scanloop \
    --pidfile /var/run/hp-netscan.pid -b -m
  echo $?
}

stop() {
  echo "Stopping hp_netscan"
  start-stop-daemon --stop --exec /bin/bash \
    --pidfile /var/run/hp-netscan.pid
  echo $?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  *)
    echo "Usage: $0 {start|stop}"
esac
